#! /usr/bin/env bash

repo="http://dev.verticallabs.ca/git/weltel.git"
script_dir=`dirname $(readlink -f $0)`
deploy_dir=`dirname $(readlink -f $script_dir)`

cd $deploy_dir
local_head=`git rev-list --max-count=1 deploy 2>/dev/null` 
remote_head=`git ls-remote $repo | grep ltbi | awk '{print $1}' 2>/dev/null` 

echo "Local head is   $local_head"
echo "Remote head is  $remote_head"

if [ -n "$remote_head" ] && [ -n "$local_head" ] && [ "$local_head" != "$remote_head" ]; then
  echo "Update needed"
  exit 1;
else
  echo "No update needed"
  exit 0;
fi
