#! /usr/bin/env bash

script_dir=`dirname $(readlink -f $0)`
deploy_dir=`dirname $(readlink -f $script_dir)`

cd $deploy_dir
cp config/app_config.yml config/deployments/local/app_config.yml
cp config/database.yml config/deployments/local/database.yml
bundle exec cap local deploy 2>&1 > update.log
